### ISSUE TITLE
Gyro sensitivity defines were updated reversed

### ISSUE THREAD

**Issue by SimonNejmann** [adafruit/Adafruit_FXAS21002C#3]
in Adafruit_FXAS21002C.h I thought that the sensitivity defines looks a bit strange, as it implies that the precision goes up as the range is increased:

#define GYRO_SENSITIVITY_250DPS  (0.0625F)    // Page 9 of NXP datasheet FXAS21002C
#define GYRO_SENSITIVITY_500DPS  (0.03125F)   // ..
#define GYRO_SENSITIVITY_1000DPS (0.015625F)  // ..
#define GYRO_SENSITIVITY_2000DPS (0.0078125F) // ..

After checking the datasheet it seems that the update was done in reverse order, as can be seen in table 35 on page 40:

Table 35. Selectable Full Scale Ranges
FS1	FS0	Range (dps)	Nominal Sensitivity (mdps/LSB)
0	0	±2000		62.5
0	1	±1000		31.25
1	0	±500		15.625
1	1	±250		7.8125

**Comment by microbuilder** [comment]
Ugg, just fixed this and ticked the version up. Thanks for taking the time to raise an issue.
